theme: jekyll-theme-slate
title: Welcome to the Choco Hut Homepage!
description: I have a passion for chocolate and hope to share that with you all. Have a look at the featured section for my latest creations!
